name: 编译适用于Redmi Book Pro16 -2025 ubuntu6.11.0-26-generic硬件驱动

on:
  workflow_dispatch:
    inputs:
      kernel_version:
        default: '6.11.0-26-generic'
        required: true
        description: '内核完整版本'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 克隆仓库
        uses: actions/checkout@v3

      - name: 安装编译依赖
        run: |
          sudo apt-get update -y
          sudo apt-get install -y build-essential dkms git wget cpio bc

      - name: 安装目标内核头文件
        run: |
          KERNEL=${{ github.event.inputs.kernel_version }}
          sudo apt-get install -y linux-headers-${KERNEL}
          ls /usr/src/linux-headers-${KERNEL}

      - name: 下载驱动源码
        run: |
          git clone https://git.kernel.org/pub/scm/linux/kernel/git/iwlwifi/backport-iwlwifi.git
          cd backport-iwlwifi
          MAIN=$(echo $KERNEL | cut -d. -f1-2)
          if git branch -a | grep -q "backport-${MAIN}.y"; then
            git checkout backport-${MAIN}.y
          else
            git checkout master
          fi

      - name: 编译驱动
        run: |
          cd backport-iwlwifi
          make defconfig-iwlwifi-public
          make -j$(nproc)
          ls -la drivers/net/wireless/intel/iwlwifi/

      - name: 打包驱动与脚本
        run: |
          cd backport-iwlwifi
          mkdir -p ../../pkg
          cp drivers/net/wireless/intel/iwlwifi/*.ko ../../pkg/
          cp drivers/bluetooth/btintel.ko ../../pkg/
          echo '#!/bin/bash' > ../../pkg/install.sh
          echo 'sudo insmod iwlwifi.ko' >> ../../pkg/install.sh
          echo 'sudo insmod iwlmvm.ko' >> ../../pkg/install.sh
          echo 'sudo insmod btintel.ko' >> ../../pkg/install.sh
          echo 'sudo systemctl start bluetooth' >> ../../pkg/install.sh
          chmod +x ../../pkg/install.sh
          cd ..
          tar -czvf ax203-6.11.0-26.tar.gz pkg/

      - name: 上传编译产物
        uses: actions/upload-artifact@v4
        with:
          name: ax203-driver
          path: ax203-6.11.0-26.tar.gz

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: 下载产物
        uses: actions/download-artifact@v4
        with:
          name: ax203-driver

      - name: 创建Release
        id: rel
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v6.11.0-26
          release_name: AX203 for 6.11.0-26-generic
          body: 'WiFi/蓝牙驱动，适用于6.11.0-26-generic内核'

      - name: 上传资产
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.rel.outputs.upload_url }}
          asset_path: ./ax203-6.11.0-26.tar.gz
          asset_name: ax203-6.11.0-26.tar.gz
          asset_content_type: application/gzip
